"""empty message

Revision ID: 34b8580cb5df
Revises: 101a6f7ce91b
Create Date: 2018-11-14 16:45:04.979146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34b8580cb5df'
down_revision = '101a6f7ce91b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('task_type', sa.Enum('VALID', 'INVALID', name='tasktype'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'task_type')
    # ### end Alembic commands ###
